# Generated by Django 3.2.25 on 2025-07-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('matricula', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('nombre_tutor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Tutor')),
                ('telefono_tutor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Tutor')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelIngles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Basico', max_length=30, verbose_name='Nombre del Nivel')),
                ('sub_nivel', models.CharField(blank=True, default='A1', help_text='A1, A2, B1, B2, C1, C2', max_length=10, null=True, verbose_name='Subnivel')),
            ],
            options={
                'verbose_name': 'Nivel de Ingles',
                'verbose_name_plural': 'Niveles de Ingles',
                'ordering': ['nombre', 'sub_nivel'],
                'unique_together': {('nombre', 'sub_nivel')},
            },
        ),
        migrations.CreateModel(
            name='Reinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reinscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Reinscripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Reinscripción')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.nivelingles', verbose_name='Nivel de Reinscripción')),
            ],
            options={
                'verbose_name': 'Reinscripción',
                'verbose_name_plural': 'Reinscripciones',
                'unique_together': {('alumno', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Inscripción')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.nivelingles', verbose_name='Nivel de Inscripción')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('alumno', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='GrupoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.nivelingles', verbose_name='Nivel del Grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Alumno',
                'verbose_name_plural': 'Grupos de Alumnos',
                'unique_together': {('alumno', 'nivel')},
            },
        ),
    ]
