# Generated by Django 3.2.25 on 2025-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_nuevo',
            field=models.BooleanField(default=False, verbose_name='¿Es alumno nuevo?'),
        ),
    ]
