# Generated by Django 3.2.25 on 2025-08-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_es_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dia_pago_preferido',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (10, '10'), (15, '15'), (18, '18'), (26, '26'), (30, '30')], default=5, verbose_name='Día de Pago Preferido'),
        ),
    ]
