# Generated by Django 3.2.25 on 2025-07-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.nivelingles', verbose_name='Nivel Asociado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nivel__nombre', 'nombre'],
                'unique_together': {('nombre', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='GrupoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo', verbose_name='Grupo Asignado')),
            ],
            options={
                'verbose_name': 'Asignación de Grupo',
                'verbose_name_plural': 'Asignaciones de Grupos',
                'ordering': ['grupo__nivel__nombre', 'grupo__nombre', 'alumno__apellido'],
                'unique_together': {('alumno', 'grupo')},
            },
        ),
    ]
