# Generated by Django 3.2.25 on 2025-07-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Descuento')),
                ('meses_anticipo', models.IntegerField(help_text='Número de meses de anticipación para aplicar el descuento', unique=True, verbose_name='Meses de Anticipo')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej. 0.05 para 5%', max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Recargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Recargo')),
                ('porcentaje_por_dia', models.DecimalField(decimal_places=2, help_text='Ej. 0.01 para 1% diario', max_digits=5, verbose_name='Porcentaje por Día')),
            ],
            options={
                'verbose_name': 'Recargo',
                'verbose_name_plural': 'Recargos',
            },
        ),
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, help_text='1=Enero … 12=Diciembre', verbose_name='Mes')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto_base', models.DecimalField(decimal_places=2, default=650.0, max_digits=10, verbose_name='Monto Base')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Final Pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_pago_actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización del Pago')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegiaturas.descuento', verbose_name='Descuento Aplicado')),
                ('recargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegiaturas.recargo', verbose_name='Recargo Aplicado')),
            ],
            options={
                'verbose_name': 'Colegiatura',
                'verbose_name_plural': 'Colegiaturas',
                'unique_together': {('alumno', 'anio', 'mes')},
            },
        ),
    ]
