# Generated by Django 3.2.25 on 2025-07-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegiaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegiatura',
            options={'ordering': ['anio', 'mes', 'alumno__apellido', 'alumno__nombre'], 'verbose_name': 'Colegiatura', 'verbose_name_plural': 'Colegiaturas'},
        ),
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['meses_anticipo'], 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterModelOptions(
            name='recargo',
            options={'ordering': ['-porcentaje_por_dia'], 'verbose_name': 'Recargo', 'verbose_name_plural': 'Recargos'},
        ),
        migrations.RenameField(
            model_name='colegiatura',
            old_name='fecha_creacion',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='fecha_pago_actualizacion',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='monto_final',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='recargo',
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento Aplicado'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='descuento_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegiaturas.descuento', verbose_name='Descuento Usado'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Atrasado', 'Atrasado')], default='Pendiente', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='recargo_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Recargo Aplicado'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='recargo_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegiaturas.recargo', verbose_name='Recargo Usado'),
        ),
    ]
