# Generated by Django 3.2.25 on 2026-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegiaturas', '0002_auto_20250723_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegiatura',
            name='fecha_auditoria_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Auditoría de Pago'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='periodo_pago',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Periodo de Pago'),
        ),
    ]
